AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - spec/integration/dummy/**


Gemspec/DuplicatedAssignment:
  Enabled: false


Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false


Naming/MemoizedInstanceVariableName:
  Enabled: false


Layout/CaseIndentation:
  EnforcedStyle: end
  SupportedStyles:
    - case
    - end
  IndentOneStep: true

Layout/LineLength:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space


Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*_spec.rb


Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SafeNavigation:
  Enabled: false # not available before 2.3

Style/SignalException:
  EnforcedStyle: only_raise

Style/TrivialAccessors:
  AllowPredicates: true
