inherit_gem:
  rubocop-config: default.yml

AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: False
  Exclude:
    - gemfiles/**/*
    - spec/integration/dummy/**/*
    - vendor/**/*

Layout/LineLength:
  Exclude:
    - spec/**/*

RSpec/MultipleMemoizedHelpers:
  Max: 15
