AllCops:
  Include:
    - '**/*.rb'
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/RaiseArgs:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/CaseIndentation:
  EnforcedStyle: end
  SupportedStyles:
    - case
    - end
  IndentOneStep: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true
