dist: xenial
language: ruby
rvm:
- 2.6.5
- 2.5.7
- 2.4.9
- 2.3.8
gemfile:
- gemfiles/Gemfile.rails-6-0
- gemfiles/Gemfile.rails-5-2
- gemfiles/Gemfile.rails-5-1
- gemfiles/Gemfile.rails-5-0
- gemfiles/Gemfile.rails-4-2
- gemfiles/Gemfile.rails-master
before_install:
- sudo apt-get install -qy rabbitmq-server
- echo yes | rvm gemset delete global
- gem install bundler -v'~>1.0'
script:
- bundle exec rake spec:msgr
- bundle exec rake spec:integration
jobs:
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-master
  exclude:
  - rvm: 2.6.5
    gemfile: gemfiles/Gemfile.rails-4-2
  - rvm: 2.4.9
    gemfile: gemfiles/Gemfile.rails-6-0
  - rvm: 2.3.8
    gemfile: gemfiles/Gemfile.rails-6-0
  - rvm: 2.4.9
    gemfile: gemfiles/Gemfile.rails-master
  - rvm: 2.3.8
    gemfile: gemfiles/Gemfile.rails-master
