sudo : false
language: ruby
bundler_args: --without development
services:
  - rabbitmq
rvm:
  - '2.3.1'
  - '2.2.5'
  - '2.1.10'
  - '2.0'
  - jruby
  - rbx
gemfile:
  - gemfiles/Gemfile.rails-4-2
  - gemfiles/Gemfile.rails-4-1
  - gemfiles/Gemfile.rails-4-0
env:
  - BUNNY_VERSION="~> 2.0"
  - BUNNY_VERSION="~> 1.5"
  - BUNNY_VERSION="~> 1.4.0"
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx
script:
  - bundle exec rake spec:msgr
  - bundle exec rake spec:integration
