dist: trusty
sudo: false
language: ruby
services:
- rabbitmq
rvm:
- 2.6.0
- 2.5.3
- 2.4.5
- 2.3.8
gemfile:
- gemfiles/Gemfile.rails-5-2
- gemfiles/Gemfile.rails-5-1
- gemfiles/Gemfile.rails-5-0
- gemfiles/Gemfile.rails-4-2
- gemfiles/Gemfile.rails-master
before_install:
- gem update --system
- gem install bundler
script:
- bundle exec rake spec:msgr
- bundle exec rake spec:integration
jobs:
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-master
  include:
    - stage: Beta release
      rvm: 2.6.0
      script: echo "Deploy to rubygems.org..."
      deploy:
        provider: rubygems
        api_key:
          secure: g8icPMdxEmbpBzSRCDmR3uB+1Zhu7tGq3h0cVbGUka2Ni1NiEiQo3LCDzbMp+L7AXH5RhdsG9FTViIAyCy9YENqZ1+jzrQGeADx0KnJZb6F81/SyumeUld0zdkzDbe1aUCJWz2WnEk12aLMPLNPRmDE7wub+od7gJEEv2SsKObo=
        gem: msgr
        on:
          branch: master
          repo: jgraichen/msgr

