language: ruby
bundler_args: --without development
services:
  - rabbitmq
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby
  - rbx
gemfile:
  - gemfiles/Gemfile.rails-3-2
  - gemfiles/Gemfile.rails-4-0
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx
before_install:
  - gem install json -v '1.8.1'
  - gem install minitest -v '4.7.5'
script:
  - bundle exec rake spec:msgr
  - bundle exec rake spec:integration
