language: ruby
bundler_args: --without development
services:
  - rabbitmq
rvm:
  - '2.1'
  - '2.0'
  - '1.9.3'
  - jruby
  - rbx
gemfile:
  - gemfiles/Gemfile.rails-4-1
  - gemfiles/Gemfile.rails-4-0
  - gemfiles/Gemfile.rails-3-2
env:
  - BUNNY_VERSION="~> 1.6"
  - BUNNY_VERSION="~> 1.5.0"
  - BUNNY_VERSION="~> 1.4.0"
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx
script:
  - bundle exec rake spec:msgr
  - bundle exec rake spec:integration
