dist: xenial
language: ruby
rvm:
  - 2.7.0
  - 2.6.5
  - 2.5.7
gemfile:
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_60.gemfile
  - gemfiles/rails_master.gemfile
before_install:
  - sudo apt-get install -qy rabbitmq-server
  - echo yes | rvm gemset delete global
  - gem install bundler -v'~>1.0'
script:
  - bundle exec rake spec:msgr
  - bundle exec rake spec:integration
jobs:
  allow_failures:
    - gemfile: gemfiles/rails_master.gemfile
  exclude:
    - rvm: 2.7.0
      gemfile: gemfiles/rails_42.gemfile
    - rvm: 2.6.5
      gemfile: gemfiles/rails_42.gemfile
