common: &common
  uri: <%= ENV.fetch("AMQP_SERVER", "amqp://localhost/") %>

test:
  <<: *common
  pool_class: Msgr::TestPool
  raise_exceptions: true

development:
  <<: *common

production:
  <<: *common
