name: Lint
on: [push]
jobs:
  rubocop:
    name: rubocop
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
        env:
          BUNDLE_WITHOUT: development
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3

      - name: Install dependencies
        run: |
          sudo apt-get install --quiet --yes libsqlite3-dev

      - name: Run rubocop
        run: bundle exec rubocop --parallel --color
