name: Lint
on: [push]
jobs:
  rubocop:
    name: rubocop
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
        env:
          BUNDLE_WITHOUT: development
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3

      - name: Run rubocop
        run: bundle exec rubocop --parallel --color
